import Head from 'next/head'
import Image from 'next/image'
import Phases from '../components/Phases'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="border-2 border-solid border-black text-black m-1 h-auto h-min-screen">
        <div className="border-2 border-solid border-red-500 p-2 flex flex-row flex-wrap justify-start font-inter">      
          <div className="border-2 border-solid border-blue-500 flex flex-row flex-wrap justify-start">
            <div className="font-light text-lg border-2 border-solid border-purple-500 w-7/12 h-fit">
              <b>6DoS</b> is an Art project between 10 friends who met on the Internet. Composing of musicians, visual artists, engineers, and community organizers, we are documenting every step we take for collective creation where there is no individual ownership of the final work. Divided into phases, precise and categorical participation is going to guide the creative direction of this project. We hope this project serves to provide a lasting impression and guidance towards Art as a practice of care and passion. 
            </div>           
          </div>
          <div className="mt-20 border-2 border-solid border-yellow-500 w-full flex flex-row flex-wrap justify-start">
            <Phases />
          </div>
          <div className="mt-20 border-2 border-solid border-yellow-500 w-full flex flex-row flex-wrap justify-start">
            <div>
              <button>
                JOIN US
              </button>
            </div>
          </div>          
        </div>
      </main>
    </div>
  )
}
